features:
  node_user_picture: 1
  comment_user_picture: 1
  comment_user_verification: 1
  favicon: 1
logo:
  use_default: 0
  path: 'public://logo_borde.png'
favicon:
  use_default: 0
  path: 'public://favicon_borde_0.png'
  mimetype: image/png
b4_top_container: container
b4_top_container_config: ''
b4_body_schema: none
b4_body_bg_schema: none
b4_navbar_schema: none
b4_navbar_bg_schema: none
b4_footer_schema: none
b4_footer_bg_schema: none
subtheme_folder: themes/custom
subtheme_name: 'B4 subtheme'
subtheme_machine_name: b4subtheme
